import pandas as pd
import re
from collections import OrderedDict

df = pd.read_excel(r"D:\results\new_dataset_cleaned.xlsx", dtype=str).fillna('')

exclusion_categories = [
    'Communication',
    'Agricultural Engineering',
    'Agriculture, Dairy & Animal Science',
    'Agriculture, Dairy & Animal Science; Veterinary Sciences; Zoology',
    'Agriculture, Multidisciplinary',
    'Agriculture, Multidisciplinary; Food Science & Technology',
    'Agriculture, Multidisciplinary; Genetics & Heredity',
    'Agronomy',
    'Agronomy; Genetics & Heredity',
    'Agronomy; Plant Sciences; Remote Sensing',
    'Allergy',
    'Allergy; Immunology',
    'Anesthesiology',
    'Anesthesiology; Clinical Neurology',
    'Anesthesiology; Critical Care Medicine',
    'Astronomy & Astrophysics; Geochemistry & Geophysics; Meteorology & Atmospheric Sciences; Remote Sensing; Telecommunications',
    'Biochemical Research Methods; Plant Sciences',
    'Biochemistry & Molecular Biology; Food Science & Technology',
    'Biochemistry & Molecular Biology; Zoology',
    'Business',
    'Business, Finance; Economics; Mathematics, Interdisciplinary Applications; Social Sciences, Mathematical Methods; Statistics & Probability',
    'Business; Engineering, Industrial; Management',
    'Business; Regional & Urban Planning',
    'Chemistry, Applied; Food Science & Technology; Nutrition & Dietetics',
    'Chemistry, Medicinal; Food Science & Technology',
    'Communication',
    'Construction & Building Technology; Engineering, Environmental; Engineering, Civil',
    'Cultural Studies; Education & Educational Research',
    'Ecology; Environmental Sciences',
    'Ecology; Forestry',
    'Ecology; Microbiology',
    'Economics; Health Care Sciences & Services; Health Policy & Services',
    'Economics; Health Care Sciences & Services; Health Policy & Services; Medicine, General & Internal',
    'Economics; Health Care Sciences & Services; Health Policy & Services; Pharmacology & Pharmacy',
    'Education & Educational Research',
    'Education & Educational Research; Education, Scientific Disciplines',
    'Education, Scientific Disciplines',
    'Education, Scientific Disciplines; Health Care Sciences & Services',
    'Energy & Fuels',
    'Engineering, Civil',
    'Engineering, Environmental; Engineering, Civil; Environmental Sciences; Statistics & Probability; Water Resources',
    'Engineering, Environmental; Environmental Sciences',
    'Engineering, Environmental; Environmental Sciences; Public, Environmental & Occupational Health; Water Resources',
    'Engineering, Environmental; Environmental Sciences; Water Resources',
    'Engineering, Geological',
    'Engineering, Geological',
    'Engineering, Industrial; Engineering, Manufacturing; Operations Research & Management Science',
    'Engineering, Industrial; Ergonomics',
    'Environmental Sciences; Geosciences, Multidisciplinary; Remote Sensing; Imaging Science & Photographic Technology',
    'Environmental Sciences; Meteorology & Atmospheric Sciences',
    'Environmental Sciences; Public, Environmental & Occupational Health; Meteorology & Atmospheric Sciences',
    'Environmental Sciences; Toxicology; Water Resources',
    'Environmental Sciences; Water Resources',
    'Ethics; Information Science & Library Science; Philosophy',
    'Ethics; Nursing',
    'Fisheries',
    'Food Science & Technology',
    'Food Science & Technology; Nutrition & Dietetics',
    'Food Science & Technology; Pharmacology & Pharmacy',
    'Food Science & Technology; Toxicology',
    'Forestry',
    'Genetics & Heredity; Psychiatry',
    'Geochemistry & Geophysics',
    'Geochemistry & Geophysics; Engineering, Electrical & Electronic; Remote Sensing; Imaging Science & Photographic Technology',
    'Geography, Physical; Geosciences, Multidisciplinary; Remote Sensing; Imaging Science & Photographic Technology',
    'Geosciences, Multidisciplinary',
    'Geosciences, Multidisciplinary; Meteorology & Atmospheric Sciences',
    'History & Philosophy Of Science',
    'History & Philosophy Of Science; Multidisciplinary Sciences',
    'Horticulture',
    'Immunology; Infectious Diseases; Virology',
    'Immunology; Virology',
    'Information Science & Library Science',
    'Law',
    'Management',
    'Materials Science, Multidisciplinary; Metallurgy & Metallurgical Engineering',
    'Medicine, Research & Experimental; Veterinary Sciences',
    'Meteorology & Atmospheric Sciences',
    'Microbiology; Mycology',
    'Microbiology; Parasitology; Virology',
    'Microbiology; Pharmacology & Pharmacy',
    'Microbiology; Virology',
    'Neurosciences; Pharmacology & Pharmacy; Psychiatry',
    'Nursing',
    'Nutrition & Dietetics',
    'Optics; Physics, Applied; Physics, Condensed Matter',
    'Pathology; Veterinary Sciences',
    'Peripheral Vascular Disease',
    'Physics, Fluids & Plasmas',
    'Physics, Fluids & Plasmas; Physics, Mathematical',
    'Physiology; Sport Sciences',
    'Plant Sciences',
    'Plant Sciences; Chemistry, Medicinal; Integrative & Complementary Medicine; Pharmacology & Pharmacy',
    'Psychiatry',
    'Psychology, Clinical; Psychiatry; Psychology',
    'Psychology, Developmental; Psychology, Experimental',
    'Psychology, Developmental; Psychology; Psychology, Experimental',
    'Psychology; Psychology, Experimental',
    'Public, Environmental & Occupational Health; Social Work',
    'Public, Environmental & Occupational Health; Tropical Medicine',
    'Quantum Science & Technology; Optics',
    'Remote Sensing',
    'Sociology',
    'Sport Sciences',
    'Substance Abuse',
    'Substance Abuse; Psychiatry',
    'Substance Abuse; Public, Environmental & Occupational Health',
    'Surgery; Peripheral Vascular Disease',
    'Telecommunications',
    'Thermodynamics',
    'Thermodynamics',
    'Thermodynamics; Energy & Fuels; Engineering, Mechanical; Mechanics',
    'Toxicology; Tropical Medicine; Zoology',
    'Tropical Medicine',
    'Veterinary Sciences',
    'Virology',
    'Zoology'
]

df = df[~df['WoS Categories'].isin(exclusion_categories)]

raw_onco = [
'acute lymphoblastic leukemia', 'acute myeloid leukemia', 'adrenal carcinoma', 'adrenal neoplasm', 'adenocarcinoma', 'adenocarcinoma of the colon', 
'ampullary adenocarcinoma', 'anal carcinoma', 'anaplastic thyroid carcinoma', 'astrocytomas', 'basal cell skin cancer', 'b-cell lymphomas', 'bilary tract cancers', 
'bladder cancer', 'bone cancer', 'bone cancers', 'brain cancer', 'brainstem neoplasm', 'brainstem tumor', 'brain tumour', 'breast cancer', 'breast carcinoma', 'carcinoma', 
'carcinomas of unknown primary', 'castleman disease', 'clear-cell renal cell carcinoma', 'ca125', 'central nervous system cancers', 'cerebellum tumors', 'cervical adenocarcinoma', 
'cervical cancer', 'cervical carcinoma', 'chordoma', 'chronic lymphocytic leukemia/small lymphocytic lymphoma', 'chronic myeloid leukemia', 'colon cancer', 
'colorectal cancer', 'cutaneous melanoma', 'cutaneous squamous cell carcinoma', 'cutaneous tumors', 'dermatofibrosarcoma protuberans', 'desmoid tumor', 
'desmoid tumors', 'diffuse intrinsic pontine glioma', 'endometrial cancer', 'endometrial stromal sarcoma', 'esophageal adenocarcinoma', 'esophageal and esophagogastric junction cancers', 
'esophageal cancer', 'ewing sarcoma', 'ewing tumor', 'ewing tumors', 'fibrosarcoma', 'gallbladder cancer', 'gastric cardiac cancer', 'gastric cancer', 
'gastroesophageal cancer', 'gastroesophageal junction cancer', 'gastrointestinal stromal tumors', 'gastrointestinal tumor', 'gestational trophoblastic neoplasia', 
'giant cell fibroblastoma', 'giant cell tumor of bone', 'glial fibrillary acidic protein', 'hairy cell leukemia', 'head and neck cancer', 'head and neck cancers', 
'hemangioendothelioma', 'hepatobiliary cancers', 'hepatocellular carcinoma', 'histiocytic cell neoplasm', 'histiocytic neoplasms', 'hodgkin lymphoma', 'kaposi sarcoma', 
'keratoacanthoma', 'kidney cancer', 'laryngeal carcinoma', 'laryngopharyngeal cancer', 'leiomyosarcoma', 'leukemia', 'liposarcoma', 'low-grade myofibroblastic sarcoma', 
'lung cancer', 'lung carcinoma', 'lung papillary adenocarcinoma', 'lymphatic neoplasm', 'lymphoid neoplasm', 'lymphoma', 'malignancy', 'mediastinal tumors', 'medulloblastoma', 
'melanoma', 'melanoma: cutaneous', 'melanoma: uveal', 'merkel cell carcinoma', 'mesenchymal neoplasms', 'mesothelioma', 'mesothelioma tumor', 'mesothelioma: peritoneal', 
'mesothelioma: pleural', 'metastasis', 'metastatic melanoma', 'multiple cancers', 'multiple myeloma', 'myelodysplastic syndromes', 'myeloproliferative neoplasms', 
'myeloid/lymphoid neoplasms with eosinophilia and tyrosine kinase gene fusions', 'nasopharyngeal cancer', 'nasopharyngeal neoplasms', 'neck tumor', 'neoplasms', 'neoplasm', 
'neoplastic', 'nephroblastoma', 'neuroblastoma', 'neuroendocrine adenocarcinoma', 'neuroendocrine adenocarcinomas', 'neuroendocrine and adrenal tumors', 'neuroendocrine carcinoma', 
'neuroendocrine tumors', 'neurogenic tumor', 'non-small cell lung cancer', 'occult cancer', 'occult malignancy', 'occult primary', 'occult primary cancer', 'occult primary neoplasm', 
'oncohematologic malignancies', 'oral squamous cell carcinoma', 'osteosarcoma tumor', 'ovarian cancer', 'ovarian cancer/fallopian tube cancer/primary peritoneal cancer', 'ovarian carcinoma', 
'pancreatic adenocarcinoma', 'pancreatic cancer', 'pancreatic duct carcinoma', 'pancreatic neuroendocrine tumors', 'paraganglioma', 'parathyroid cancer', 'parathyroid cancers', 
'parathyroid carcinoma', 'parathyroid carcinomas', 'penile cancer', 'pharyngeal cancer', 'pineal tumor', 'pituitary tumors', 'pleomorphic adenoma', 'pleural cancer', 'pleural mesothelioma', 
'posterior fossa tumors', 'primary bone tumor', 'primary cutaneous lymphomas', 'prostate cancer', 'prostate cancer tumor', 'prostate carcinoma', 'prostate malignancy', 'rectal cancer', 
'rectal carcinoma', 'renal cancer', 'renal carcinoma', 'renal cell carcinoma', 'renal malignancy', 'renal malignant tumor', 'rhabdomyosarcoma', 'sarcoma', 'sarcoma tumor', 'skin cancer', 
'skin carcinoma', 'skin tumors', 'small bowel adenocarcinoma', 'small cell lung cancer', 'small cell lung cancers', 'smarcb1', 'soft tissue sarcoma', 'spinal bone tumor', 
'squamous cell carcinoma', 'squamous cell skin cancer', 'stomach cancer', 'stomach tumors', 'synovial sarcoma', 'systemic light chain amyloidosis', 'systemic mastocytosis', 
't-cell lymphomas', 'testicular cancer', 'testicular tumors', 'thymic carcinoma', 'thymic epithelial tumor', 'thymomas and thymic carcinomas', 'thyroid cancer', 'thyroid carcinoma', 
'thyroid cytopathology', 'thyroid fine-needle aspiration', 'thyroid neoplasm', 'thyroid tumors', 'tumor', 'tumors', 'uterine cancer', 'uterine carcinoma', 'uterine malignancies', 
'uterine neoplasms', 'uterine sarcoma', 'vaginal cancer', 'various cancers', 'vulvar cancer', 'vulvar squamous cell carcinoma', 'waldenström macroglobulinemia/lymphoplasmacytic lymphoma', 
'wilms tumor', 'CAR-T cell', 'car-t lymphocytes', 'car-t cell therapy', 'pancancer', 'Craniopharyngioma', 'solid tumor oncology', 'circulating tumor DNA', 'ctDNA', 'breast magnetic resonance imaging', 
'breast impc', 'breast pathological images', 'breast invasive micropapillary carcinoma', 'mastectomy', 'breast specimen', 'breast mr images', 'breast mris', 'lumpectomy', 'breast lumpectomy', 'breast lymph nodes', 
'breast carcinoma', 'invasive ductal carcinoma', 'breast carcinomas', 'breast adenocarcinoma', 'breast adenocarcinomas', 'breast malignancy', 'breast malignancies', 'tnbc', 'triple-negative breast cancer', 'invasive breast carcinoma', 
'ductal carcinoma in situ', 'breast ductal carcinoma in situ', 'invasive lobular carcinoma', 'breast ultrasound', 'mammograms', 'breast masses', 'breast tumor', 'breast tumors', 'mcf-7', 'breast neoplasm', 'breast neoplasms', 'abus', 
'mammography', 'mammogram', 'bi-rads', 'lobular carcinoma', 'breast biopsies', 'breast biopsy', 'colorectal cancer', 'colorectal neoplasm', 'rectal swabs', 'colorectal tumor', 'rectal carcinoma', 'colorectal neoplastic', 'colorectal datasets', 
'colorectal epithelial cells', 'rectal adenocarcinoma', 'colorectal liver metastases', 'colorectal neoplasia', 'colorectal carcinoma', 'colorectal carcinomas', 'msi-h', 'colorectal adenocarcinoma', 'colorectal adenocarcinomas', 'colorectal malignancy', 
'colon carcinoma', 'colon carcinomas', 'colon adenocarcinoma', 'colon adenocarcinomas', 'colon malignancy', 'colon malignancies', 'colorectal malignancies', 'microsatellite instability', 'msi', 'colorectal cancers', 'colon cancer', 'colon cancers', 'rectal cancer', 
'rectal cancers', 'colon tumor', 'colon tumors', 'rectal tumor', 'rectal tumors', 'colon neoplasm', 'colon neoplasms', 'rectal neoplasm', 'rectal neoplasms', 'adenocarcinoma of the colon', 'adenocarcinoma of the rectum', 'familial adenomatous polyposis', 'lynch syndrome', 
'rectum', 'sigmoid colon', 'anal cancer', 'anal cancers', 'anal tumor', 'anal tumors', 'anal neoplasm', 'anal neoplasms', 'squamous cell carcinoma of the anus', 'anal squamous cell carcinoma', 'anorectal cancer', 'anorectal cancers', 'anorectal tumor', 'anorectal tumors', 
'anorectal neoplasm', 'anorectal neoplasms', 'perianal cancer', 'perianal cancers', 'perianal tumor', 'perianal tumors', 'perianal neoplasm', 'perianal neoplasms', 'prostate cancer', 'prostate carcinoma', 'tmprss2-erg', 'prostate cancers', 'prostate tumor', 
'prostate tumors', 'prostate neoplasm', 'prostate neoplasms', 'prostatic adenocarcinoma', 'gleason score', 'androgen-dependent prostate cancer', 'benign prostatic hyperplasia', 'abiraterone', 'enzalutamide', 'prostate carcinomas', 'prostate adenocarcinoma', 
'prostate adenocarcinomas', 'prostate malignancy', 'prostate malignancies', 'apalutamide', 'castration-resistant', 'psa', 'prostate biopsy', 'lung cancer', 'thoracic cancer', 'lung papillary adenocarcinoma', 'ros1', 'thoracic cancers', 'lung cavity', 'lung cancers', 
'lung tumor', 'lung tumors', 'lung neoplasm', 'lung neoplasms', 'non-small cell lung cancer', 'non-small cell lung cancers', 'small cell lung cancer', 'small cell lung cancers', 'bronchoalveolar carcinoma', 'lung biopsy', 'pulmonary nodules', 'bronchoscopy', 'videobronchoscopy', 
'lung squamous cell carcinoma', 'large cell lung carcinoma', 'lung carcinoma', 'lung carcinomas', 'lung adenocarcinoma', 'lung adenocarcinomas', 'lung malignancy', 'lung malignancies', 'pulmonary carcinoma', 'pulmonary carcinomas', 'pulmonary adenocarcinoma', 'pulmonary adenocarcinomas', 
'pulmonary malignancy', 'pulmonary malignancies', 'nsclc', 'sclc', 'alk mutation', 'iladc', 'brain cancer', 'posterior fossa tumors', 'whole-brain', 'brain on mri', 'encephalon cancers', 'encephalon cancer', 'encephalon malignancy', 'encephalon malignancies', 'encephalon neoplasm', 
'encephalon neoplasms', 'encephalon carcinoma', 'encephalon carcinomas', 'encephalon adenocarcinoma', 'encephalon adenocarcinomas', 'tumor of the encephalon', 'brain tissue', 'tumors of the encephalon', 'cancer of the encephalon', 'cancers of the encephalon', 
'malignancy of the encephalon', 'malignancies of the encephalon', 'neoplasm of the encephalon', 'neoplasms of the encephalon', 'carcinoma of the encephalon', 'carcinomas of the encephalon', 'neoplastic hemorrhage', 'neoplastic and non-neoplastic intracerebral hemorrhage', 
'encephalon tumors', 'encephalon tumor', 'electroencephalography', 'retinoblastoma', 'central nervous system', 'cns', 'brain image', 'brain images', 'schwannomas', 'schwannoma', 'glial fibrillary acidic protein', 'gfap', 'anterior fossa tumors', 'brain cancers', 
'brain tumor', 'brain tumors', 'brain neoplasm', 'brain neoplasms', 'glioma', 'gliomas', 'astrocytoma', 'glioblastoma multiforme', 'ependymoma', 'oligodendroglioma', 'brain carcinoma', 'brain carcinomas', 'brain adenocarcinoma', 'brain adenocarcinomas', 'brain malignancy', 
'brain malignancies', 'cerebral carcinoma', 'cerebral carcinomas', 'cerebral adenocarcinoma', 'cerebral adenocarcinomas', 'cerebral malignancy', 'cerebral malignancies', 'anaplastic astrocytoma', 'medulloblastoma', 'diffuse intrinsic pontine glioma', 'astrocytomas', 'meningioma', 
'glioblastoma', 'cerebellum cancer', 'cerebellum cancers', 'cerebellum tumor', 'cerebellum tumors', 'cerebellum neoplasm', 'cerebellum neoplasms', 'corpus callosum cancer', 'corpus callosum cancers', 'corpus callosum tumor', 'corpus callosum tumors', 'corpus callosum neoplasm', 
'corpus callosum neoplasms', 'pituitary cancer', 'pituitary cancers', 'pituitary tumor', 'pituitary tumors', 'pituitary neoplasm', 'pituitary neoplasms', 'hypothalamus cancer', 'hypothalamus cancers', 'hypothalamus tumor', 'hypothalamus tumors', 'hypothalamus neoplasm', 'hypothalamus neoplasms', 
'brainstem cancer', 'brainstem cancers', 'brainstem tumor', 'brainstem tumors', 'brainstem neoplasm', 'brainstem neoplasms', 'medulla oblongata cancer', 'medulla oblongata cancers', 'medulla oblongata tumor', 'medulla oblongata tumors', 'medulla oblongata neoplasm', 'medulla oblongata neoplasms', 
'cervical cancer', 'cervical carcinoma', 'cervical carcinomas', 'cervical adenocarcinoma', 'cervical adenocarcinomas', 'cervical malignancy', 'cervical malignancies', 'cervical cancers', 'cervical tumor', 'cervical tumors', 'cervical neoplasm', 'cervical neoplasms', 'hela', 'hpv', 'pap-smear', 
'cervical intraepithelial neoplasia', 'liver cancer', 'liver cancers', 'liver carcinoma', 'liver carcinomas', 'liver adenocarcinoma', 'hepatic carcinoma', 'boundary of tumor and liver', 'hepatic carcinomas', 'hepatic adenocarcinoma', 'hepatic adenocarcinomas', 'hepatic malignancy', 'hepatic malignancies', 
'liver adenocarcinomas', 'liver malignancy', 'liver malignancies', 'liver tumor', 'liver tumors', 'liver neoplasm', 'liver neoplasms', 'hepatocellular carcinoma', 'hepatic adenoma', 
'fibrolamellar carcinoma', 'hepatic hemangioma', 'cholangiocarcinoma', 'intrahepatic cholangiocarcinoma', 'hcc', 'cirrhosis', 'hepatitis b', 'afp', 'cholangioscopy', 'stomach cancer', 
'gastroesophageal cancer', 'gastroesophageal adenocarcinoma', 'gastrointestinal tumor', 'gastroesophageal junction', 'gastric or gastroesophageal junction cancer', 'gastric cardiac cancer', 
'gastric-cancer', 'gastrin', 'gastric neoplasms', 'stomach cancers', 'gastric cancer', 'gastric cancers', 'stomach tumor', 'stomach tumors', 'gastric tumor', 'gastric tumors', 
'stomach neoplasm', 'stomach carcinoma', 'stomach carcinomas', 'stomach adenocarcinoma', 'stomach adenocarcinomas', 'stomach malignancy', 'stomach malignancies', 'gastric carcinoma', 
'gastric carcinomas', 'gastric adenocarcinoma', 'gastric adenocarcinomas', 'gastric malignancy', 'gastric malignancies', 'stomach neoplasms', 'linitis plastica', 'signet ring cell carcinoma', 
'mucosa-associated lymphoid tissue lymphoma', 'gastric neuroendocrine tumor', 'upper gastrointestinal tract carcinoma', 'gastrointestinal cancer', 'helicobacter pylori', 'endometrial cancer', 
'endometrioid', 'endometrial cancers', 'endometrial tumor', 'endometrial tumors', 'endometrial neoplasm', 'endometrial neoplasms', 'uterine cancer', 'uterine cancers', 'uterine tumor', 'uterine tumors', 'uterine neoplasm', 'uterine neoplasms', 'endometrial carcinoma', 'endometrial carcinomas', 'uterine carcinoma', 'uterine carcinomas', 'endometrial adenocarcinoma', 'endometrial adenocarcinomas', 'endometrial malignancy', 'endometrial malignancies', 'uterine adenocarcinoma', 'uterine adenocarcinomas', 'endometrioid cancer', 'endometrioid cancers', 'endometrioid tumor', 'endometrioid tumors', 'endometrioid neoplasm', 'endometrioid neoplasms', 'serous endometrial cancer', 'serous endometrial cancers', 'serous endometrial tumor', 'serous endometrial tumors', 'serous endometrial neoplasm', 'serous endometrial neoplasms', 'skin cancer', 'keratoacanthoma', 'skin tissue', 'skin cancers', 'skin tumor', 'hand tumors', 'skin tumors', 'skin neoplasm', 'cutaneous squamous cell carcinoma', 'skin neoplasms', 'basal cell carcinoma', 'skin carcinoma', 'skin carcinomas', 'skin adenocarcinoma', 'skin adenocarcinomas', 'skin malignancy', 'skin malignancies', 'ovarian cancer', 'ovarian-cancer', 'ca125', 'pax8', 'ovarian cancers', 'ovarian tumor', 'ovarian tumors', 'ovarian neoplasm', 'ovarian neoplasms', 'ovarian epithelial carcinoma', 'ovarian clear cell carcinoma', 'ovarian serous carcinoma', 'serous ovarian carcinoma', 'endometrioid ovarian carcinoma', 'clear cell ovarian carcinoma', 'ovarian carcinoma', 'ovarian carcinomas', 'ovarian adenocarcinoma', 'ovarian adenocarcinomas', 'ovarian malignancy', 'ovarian malignancies', 'mucinous ovarian carcinoma', 'fallopian tube', 'low-grade serous ovarian carcinoma', 'granulosa cell tumor', 'dysgerminoma', 'ovarian germ cell tumor', 'figo', 'adnexal masses', 'head and neck cancer', 'neck tumor', 'oral squamous cell carcinoma', 'tumors of both jaws', 'laryngopharyngeal cancer', 'oropharyngeal squamous cell carcinoma', 'opscc', 'jaws', 'dental cyst', 'teeth', 'laryngeal squamous cell carcinoma', 'neck tumors', 'head and neck', 'head and neck cancers', 'head and neck tumor', 'head and neck tumors', 'head and neck neoplasm', 'head and neck neoplasms', 'laryngeal cancer', 'laryngeal cancers', 'head-and-neck cancer', 'laryngeal tumor', 'laryngeal tumors', 'laryngeal neoplasm', 'laryngeal neoplasms', 'pharyngeal cancer', 'pharyngeal cancers', 'pharyngeal tumor', 'pharyngeal tumors', 'pharyngeal neoplasm', 'pharyngeal neoplasms', 'oropharyngeal cancer', 'oropharyngeal cancers', 'oropharyngeal tumor', 'oropharyngeal tumors', 'oropharyngeal neoplasm', 'oropharyngeal neoplasms', 'hypopharyngeal cancer', 'hypopharyngeal cancers', 'hypopharyngeal tumor', 'hypopharyngeal tumors', 'hypopharyngeal neoplasm', 'hypopharyngeal neoplasms', 'nasopharyngeal cancer', 'nasopharyngeal cancers', 'nasopharyngeal tumor', 'nasopharyngeal tumors', 'nasopharyngeal neoplasm', 'nasopharyngeal neoplasms', 'oral cancer', 'oral cancers', 'oral tumor', 'oral tumors', 'oral neoplasm', 'oral neoplasms', 'tongue cancer', 'tongue cancers', 'tongue tumor', 'tongue tumors', 'tongue neoplasm', 'tongue neoplasms', 'lip cancer', 'lip cancers', 'lip tumor', 'lip tumors', 'lip neoplasm', 'lip neoplasms', 'salivary gland cancer', 'salivary gland cancers', 'salivary gland tumor', 'salivary gland tumors', 'salivary gland neoplasm', 'salivary gland neoplasms', 'sinus cancer', 'sinus cancers', 'sinus tumor', 'sinus tumors', 'sinus neoplasm', 'sinus neoplasms', 'maxillary sinus cancer', 'maxillary sinus cancers', 'maxillary sinus tumor', 'maxillary sinus tumors', 'maxillary sinus neoplasm', 'maxillary sinus neoplasms', 'larynx cancer', 'nasopharyngeal carcinoma', 'nasopharynx', 'renal cancer', 'renal cell carcinoma', 'chronic kidney disease', 'renal malignant tumor', 'kidney renal clear cel', 'renal clear cell carcinoma', 'kidney tumour', 'nephroblastoma', 'kidney diseases', 'kidney segmentation', 'renal carcinoma', 'renal carcinomas', 'renal adenocarcinoma', 'renal adenocarcinomas', 'renal malignancy', 'renal malignancies', 'uroplakin', 'clear cell renal cell carcinoma', 'malignant renal neoplasms', 'renal neoplasm', 'cystic renal lesions', 'ccrcc', 'fuhrman grading system', 'renal cancers', 'renal tumor', 'renal tumors', 'renal neoplasms', 'kidney cancer', 'kidney cancers', 'kidney tumor', 'kidney tumors', 'kidney neoplasm', 'kidney neoplasms', 'papillary renal cell carcinoma', 'chromophobe renal cell carcinoma', 'renal oncocytoma', 'collecting duct carcinoma', 'mesothelioma', 'pleural mesothelioma', 'parathyroid cancer', 'hyperparathyroidism', 'parathyroid cancers', 'parathyroid carcinoma', 'parathyroid carcinomas', 'parathyroid adenocarcinoma', 'parathyroid adenocarcinomas', 'parathyroidectomy', 'parathyroid neoplasm', 'parathyroid neoplasms', 'parathyroid tumor', 'parathyroid tumors', 'parathyroid malignancy', 'parathyroid malignancies', 'parathyroid neoplasia', 'parathyroid neoplasias', 'cancer of the parathyroid', 'tumor of the parathyroid', 'carcinoma of the parathyroid', 'adenocarcinoma of the parathyroid', 'neoplasia of the parathyroid', 'neoplasias of the parathyroid', 'gallbladder cancer', 'gb polyps', 'neoplastic gallbladder', 'gallbladder cancers', 'gallbladder tumor', 'gallbladder tumors', 'gallbladder malignancy', 'gallbladder malignancies', 'gallbladder carcinoma', 'gallbladder carcinomas', 'gallbladder adenocarcinoma', 'gallbladder adenocarcinomas', 'gallbladder neoplasm', 'gallbladder neoplasms', 'gallbladder neoplasia', 'gallbladder neoplasias', 'tumor of the gallbladder', 'tumors of the gallbladder', 'cancer of the gallbladder', 'cancers of the gallbladder', 'malignancy of the gallbladder', 
'malignancies of the gallbladder', 'carcinoma of the gallbladder', 'carcinomas of the gallbladder', 'adenocarcinoma of the gallbladder', 'adenocarcinomas of the gallbladder', 'neoplasm of the gallbladder', 'neoplasms of the gallbladder', 'neoplasia of the gallbladder', 'neoplasias of the gallbladder', 'occult primary cancer', 'unknown primary', 'occult primary malignancy', 'occult primary neoplasm', 'occult primary carcinoma', 'occult primary adenocarcinoma', 'occult cancer', 'occult cancers', 'occult malignancy', 'occult malignancies', 'occult tumor', 'occult tumors', 'unknown primaries', 'unknown primary cancer', 'unknown primary cancers', 'unknown primary malignancy', 'unknown primary malignancies', 'unknown primary tumor', 'unknown primary tumors', 'unknown primary neoplasm', 'unknown primary neoplasms', 'unknown primary carcinoma', 'unknown primary carcinomas', 'carcinoma of unknown primary', 'carcinomas of unknown primary', 'cancer of unknown primary', 'cancers of unknown primary', 'unknown primary adenocarcinoma', 'unknown primary adenocarcinomas', 'occult carcinoma', 'occult carcinomas', 'occult adenocarcinoma', 'occult adenocarcinomas', 'occult neoplasm', 'occult neoplasms', 'unknown primary lesion', 'unknown primary lesions', 'occult primary lesion', 'occult primary lesions', 'vaginal cancer', 'vaginal cancers', 'vaginal tumor', 'vaginal squamous cell carcinoma', 'vaginal intraepithelial neoplasia', 'vaginal malignancy', 'vaginal tumors', 'vaginal neoplasm', 'vaginal carcinoma', 'vaginal carcinomas', 'vaginal adenocarcinoma', 'vaginal adenocarcinomas', 'vaginal malignancies', 'vaginal neoplasms', 'vulvar cancer', 'vulvar cancers', 'vulvar squamous cell carcinoma', 'vulvar intraepithelial neoplasia', 'vulvar malignancy', 'vulvar tumor', 'vulvar tumors', 'vulvar neoplasm', 'vulvar neoplasms', 'vulvar malignancies', 'vulvar carcinoma', 'vulvar carcinomas', 'vulvar adenocarcinoma', 'vulvar adenocarcinomas', 'penile cancer', 'penile cancers', 'penile squamous cell carcinoma', 'penile intraepithelial neoplasia', 'penile tumor', 'penile tumors', 'penile neoplasm', 'penile neoplasms', 'penile malignancy', 'penile malignancies', 'penile carcinoma', 'penile carcinomas', 'penile adenocarcinoma', 'penile adenocarcinomas', 'neuroendocrine tumors', 'neuroendocrine carcinoma', 'pleomorphic adenoma', 'parotid gland', 'salivary gland', 'neuroendocrine carcinomas', 'neuroendocrine adenocarcinoma', 'neuroendocrine adenocarcinomas', 'neuroendocrine malignancy', 'neuroendocrine malignancies', 'phaeochromocytoma', 'pheochromocytoma', 'phaeochromocytomas', 'pheochromocytomas', 'adrenal medullary tumor', 'adrenal medullary tumors', 'chromaffin cell tumor', 'chromaffin cell tumors', 'adrenal tumor', 'adrenal tumors', 'adrenal neoplasm', 'adrenal neoplasms', 'adrenal medullary neoplasm', 'adrenal medullary neoplasms', 'catecholamine-secreting tumor', 'catecholamine-secreting tumors', 'extra-adrenal paraganglioma', 'extra-adrenal paragangliomas', 'paraganglioma', 'paragangliomas', 'parasympathetic paraganglioma', 'sympathetic paraganglioma', 'carotid body tumor', 'carotid body tumors', 'chromaffin paraganglioma', 'neuroendocrine tumor', 'neuroendocrine neoplasm', 'neuroendocrine neoplasms', 'small round cell neuroendocrine tumor', 'large cell neuroendocrine tumor', 'high-grade neuroendocrine tumor', 'low-grade neuroendocrine tumor', 'sympathetic tumor', 'sympathetic tumors', 'sympathetic neoplasm', 'sympathetic neoplasms', 'parasympathetic tumor', 'parasympathetic tumors', 'parasympathetic neoplasm', 'parasympathetic neoplasms', 'SDHB mutation', 'SDHD mutation', 'VHL mutation', 'NF1 mutation', 'mediastinal tumors', 'mediastinal cancer', 'mediastinal neoplasm', 'mediastinal neoplasms', 'mediastinal tumor', 'mediastinal carcinoma', 'mediastinal carcinomas', 'mediastinal adenocarcinoma', 'mediastinal adenocarcinomas', 'mediastinal malignancy', 'mediastinal malignancies', 'thymic epithelial tumorstets', 'thymic carcinomas', 'thymomas', 'neurilemoma', 'germ cell tumor', 'anterior mediastinal mass', 'mediastinal mass', 'thymic mass', 'thymic hyperplasia', 'malignant thymoma', 'thymic neuroendocrine tumor', 'invasive thymoma', 'thymic cyst', 'germ cell tumor of the mediastinum', 'teratoma of the mediastinum', 'mediastinal teratoma', 'mediastinal seminoma', 'neurogenic tumor of the mediastinum', 'bone cancers', 'bone cancer', 'primary bone tumor', 'pelvic and sacral tumors', 'malignant bone tumor', 'pagets disease of bone', 'giant cell tumor of bone', 'chordoma', 'adamantinoma', 'chondroma', 'enchondroma', 'vertebral tumor', 'bone carcinoma', 'bone carcinomas', 'bone adenocarcinoma', 'bone adenocarcinomas', 'bone malignancy', 'bone malignancies', 'spinal bone tumor', 'coccygeal tumor', 'pelvic bone tumor', 'iliac bone tumor', 'ischial bone tumor', 'pubic bone tumor', 'scapular tumor', 'clavicular tumor', 'sternal tumor', 'rib bone tumor', 'humeral bone tumor', 'femoral bone tumor', 'tibial bone tumor', 'fibrous dysplasia of bone', 'osteoblastoma', 'osteoma', 'melanoma', 'mc1r', 'dermoscopy', 'dermatoscopy', 'cutaneous melanoma', 'malignant melanoma', 'skin melanoma', 'metastatic melanoma', 'melanocytic nevus', 'kit mutation', 'superficial spreading melanoma', 
'nodular melanoma', 'acral lentiginous melanoma', 'lentigo maligna melanoma', 'amelanotic melanoma', 'melanoma in situ', 'clark level', 'breslow depth', 'sentinel lymph node biopsy', 'immunotherapy for melanoma', 'targeted therapy for melanoma', 'melanoma staging', 'abcde criteria', 'sarcoma', 'desmoid tumors', 'desmoid tumor', 'desmin', 'mesenchymal neoplasms', 'smarcb1', 'acta2', 'myod1', 'myogenin', 'pax3-foxo1', 'pax7-foxo1', 'smooth muscle actin', 'h-caldesmon', 'sarcomas', 'soft tissue sarcoma', 'soft tissue sarcomas', 'osteosarcoma', 'osteosarcomas', 'ewing sarcoma', 'ewing sarcomas', 'leiomyosarcoma', 'leiomyosarcomas', 'liposarcoma', 'liposarcomas', 'rhabdomyosarcoma', 'rhabdomyosarcomas', 'gastrointestinal stromal tumor', 'gastrointestinal stromal tumors', 'gist', 'gists', 'epithelioid sarcoma', 'epithelioid sarcomas', 'epithelioid sarcoma of soft tissue', 'giant cell fibroblastoma', 'giant cell fibroblastomas', 'gcf', 'dermatofibrosarcoma protuberans', 'dermatofibrosarcoma', 'dfsp', 'fibrosarcoma', 'fibrosarcomas', 'low-grade myofibroblastic sarcoma', 'low-grade myofibroblastic sarcomas', 'lgms', 'low-grade fibromyxoid sarcoma', 'low-grade fibromyxoid sarcomas', 'rhabdomyosarcoma tumor', 'rhabdomyosarcoma tumors', 'leiomyosarcoma of soft tissue', 'leiomyosarcoma of uterus', 'leiomyosarcoma of stomach', 'leiomyosarcoma of retroperitoneum', 'liposarcoma of soft tissue', 'liposarcoma of retroperitoneum', 'gastrointestinal stromal tumor of stomach', 'gastrointestinal stromal tumor of small intestine', 'gastrointestinal stromal tumor of esophagus', 'gastrointestinal stromal tumors of stomach', 'gastrointestinal stromal tumors of small intestine', 'gastrointestinal stromal tumors of esophagus', 'ewing tumor', 'ewing tumors', 'ewing neoplasm', 'ewing neoplasms', 'leiomyosarcoma tumor', 'leiomyosarcoma tumors', 'leiomyosarcoma neoplasm', 'leiomyosarcoma neoplasms', 'liposarcoma tumor', 'liposarcoma tumors', 'liposarcoma neoplasm', 'liposarcoma neoplasms', 'epithelioid sarcoma tumor', 'epithelioid sarcoma tumors', 'epithelioid sarcoma neoplasm', 'epithelioid sarcoma neoplasms', 'giant cell fibroblastoma tumor', 'giant cell fibroblastoma tumors', 'giant cell fibroblastoma neoplasm', 'giant cell fibroblastoma neoplasms', 'dermatofibrosarcoma tumor', 'dermatofibrosarcoma tumors', 'dermatofibrosarcoma neoplasm', 'dermatofibrosarcoma neoplasms', 'dfsp tumor', 'dfsp tumors', 'dfsp neoplasm', 'dfsp neoplasms', 'fibrosarcoma tumor', 'fibrosarcoma tumors', 'fibrosarcoma neoplasm', 'fibrosarcoma neoplasms', 'low-grade myofibroblastic sarcoma tumor', 'low-grade myofibroblastic sarcoma tumors', 'low-grade myofibroblastic sarcoma neoplasm', 'low-grade myofibroblastic sarcoma neoplasms', 'rhabdomyosarcoma of soft tissue', 'rhabdomyosarcoma of muscles', 'rhabdomyosarcoma of connective tissue', 'rhabdomyosarcoma neoplasm', 'rhabdomyosarcoma neoplasms', 'uterine sarcoma', 'uterine sarcomas', 'endometrial stromal sarcoma', 'synovial sarcoma', 'oncohematologic malignancies', 'leukemia', 'burkitt lymphoma', 'burkitt lymphomas', 'hematologic neoplasms', 'sternal puncture', 'cd3', 'cd20', 'bcl2', 'bcl6', 'CD138', 'syndecan-1', 'cd38', 'myeloperoxidase', 'fms like tyrosine kinase 3', 'nucleophosmin', 'ccaat/enhancer binding protein alpha', 'hematologic malignancy', 'hematologic malignancies', 'mpo', 'flt3', 'npm1', 'cebpa', 'cyclic adp ribose hydrolase', 'bone marrow transplant', 'bone marrow transplantation', 'dlbcl', 'myelodysplastic syndrome', 'myeloproliferative diseases', 'myeloproliferative disease', 'myelodysplastic syndromes', 'lymphomas', 'hematological malignancies', 'blood cancer', 'blood cancers', 'myeloid neoplasm', 'myeloid neoplasms', 'histiocytic and dendritic cell neoplasms', 'dendritic cell neoplasm', 'histiocytic cell neoplasm', 'lymphoid neoplasm', 'myeloma', 'haematological malignancies', 'liquid tomors', 'leukemias', 'lymphoma', 'multiple myeloma', 'acute myeloid leukemia', 'chronic lymphocytic leukemia', 'acute lymphoblastic leukemia', 'hodgkins lymphoma', 'non-hodgkins lymphoma', 'plasma cell neoplasms', 'plasma cell neoplasm', 'bone marrow biopsy', 'myelomas', 'bladder cancer', 'malignancy in bladder', 'urothelial cell carcinoma', 'cancer of the bladder', 'bladder-cancer', 'bladder cancers', 'bladder tumor', 'bladder tumors', 'bladder neoplasm', 'bladder neoplasms', 'urothelial carcinoma', 'non-muscle invasive bladder cancer', 'muscle-invasive bladder cancer', 'squamous cell carcinoma of the bladder', 'bladder adenocarcinoma', 'transitional cell carcinoma', 'hematuria', 'bacillus calmette-guГ©rin', 'bcg therapy', 'turbt', 'nmibc', 'n-mibc', 'm-ibc', 'mibccystoscopy', 'esophageal cancer', 'esophageal tumor', 'oesophageal squamous cell carcinoma', 'oesophagectomy', 'oesophageal cancer', 'esophageal and esophagogastric junction adenocarcinomas', 'adenocarcinoma of the esophagogastric junction', 'barretts neoplasia', 'barretts esophagus', 'esophageal adenocarcinoma', 'esophageal squamous cell carcinoma', 'esophagectomy', 'dysphagia', 'gerd', 'gastroesophageal reflux disease', 'esophageal carcinoma', 'esophageal carcinomas', 'esophageal adenocarcinomas', 'esophageal malignancy', 'esophageal malignancies', 'thyroid cancer', 'american thyroid association', 'neoplasms of the thyroid gland', 'thyroid fine-needle aspiration', 'thyroid cytopathology', 'thyroid tumor', 'thyroid tumors', 'thyroid carcinoma', 
'thyroid carcinomas', 'thyroid adenocarcinoma', 'thyroid adenocarcinomas', 'thyroid malignancy', 'thyroid malignancies', 'ret', 'ret/ptc', 'thyroid nodules', 'medullary thyroid carcinoma', 'papillary thyroid carcinoma', 'follicular thyroid carcinoma', 'follicular thyroid adenoma', 'anaplastic thyroid carcinoma', 'thyroidectomy', 'tsh', 'thyroid-stimulating hormone', 'radioiodine therapy', 'testicular cancer', 'testicular cancers', 'testicular tumor', 'testicular tumors', 'testicular carcinoma', 'testicular carcinomas', 'testicular adenocarcinoma', 'testicular adenocarcinomas', 'testicular malignancy', 'testicular malignancies', 'testicular neoplasm', 'testicular neoplasms', 'germ cell tumors', 'seminoma', 'non-seminoma', 'orchiectomy', 'alpha-fetoprotein', 'beta-hcg', 'testicular mass', 'pancreatic cancer', 'pancreatic neuroendocrine neoplasms', 'autoimmune pancreatitis', 'pancreatic duct carcinoma', 'pancreatic serous cystic neoplasms', 'pancreatic cystic neoplasms', 'scn and mcn', 'pancreatic mucinous and serous cystic neoplasms', 'pancreatobiliary-type', 'pancreatic scns', 'pancreatic-cancer', 'pancreaticoduodenectomy', 'glucagon', 'men1', 'pancreatic ductal adenocarcinoma', 'pdac', 'pancreatic cancers', 'pancreatic tumor', 'pancreatic carcinoma', 'pancreatic carcinomas', 'pancreatic adenocarcinoma', 'pancreatic adenocarcinomas', 'pancreatic malignancy', 'pancreatic malignancies', 'pancreatic tumors', 'pancreatic neoplasm', 'pancreatic neoplasms', 'mucinous cystic neoplasm of the pancreas', 'intraductal papillary mucinous neoplasm', 'solid tumor', 'solid tumors', 'solid tumours', 'solid cancers', 'solid pseudopapillary neoplasm of the pancreas', 'pancreatic neuroendocrine tumors', 'pancreatic neuroendocrine tumor', 'pancreas cancer', 'pancreas tumor', 'pancreas cancers', 'pancreas tumors', 'pancreas neoplasms', 'pancreas neoplasm', 'pnet', 'various cancers', 'multiple cancers', 'nanomask', 'cancer phenotypes', 'submucosal tumors', 'brain metastasis', 'brain metastases', 'intronic long noncoding rna', 'multiple types of early-stage cancer', 'the cancer genome atlas', 'multiple sites of origin', 'bone metastatic cancer', 'cancer driver genes', 'tumor suppressor genes', 'different cancers', 'lung and colon', 'major types of cancers', 'types of cancers', 'various diseases', 'subclonal selection', 'genotype matrix', 'tumor phylogeny', 'variant allele frequencies', 'methylation data', 'cancer origin determination', 'cell lines', 'cell line', 'circulating tumor cells', 'circulating tumor cell', 'several subtypes', 'cancer spheroids', 'cancer cell model', 'multi-cancer', 'ras/mek/erk', 'ck7', 'ck18', 'ck8', 'ctnnb1', 'p63', 'p53', 'tp53', 'ck5/6', 'pd-l1', 'pdl', 'pten', 'myc', 'cdkn2a', 'various tumor', 'various tumors', 'organs-at-risk', 'oars', 'multiple cancer types', 'various carcinoma', 'various carcinomas', 'various adenocarcinoma', 'various adenocarcinomas', 'various malignancy', 'various malignancies', 'pan-cancer', 'organoid growth', 'segmentation of cscs', 'ed visit risk among patients with cancer', 'nci-60', 'plwc', 'tumor exomes', 'vascular endothelial growth factor receptor', 'vegfr-2', 'tumor angiogenic factors', 'extracellular matrix', 'breast-colorectal-endometrial', 'more than two hd cancers of interest', 'human tumors', 'multi-cancer-type', 'tumor type prediction', 'various cancer types', 'pancancer', 
'different cancer types', 'cancer detection across multiple types', 'broad cancer diagnostic model', 'pan cancer', 'multi-cancer detection', 'tumor agnostic', 'common cancer markers', 'cancer diagnosis', 'deep learning for various cancer detection', 'various atll cancer'
]

raw_ai = ['Linear Regression', 'Logistic Regression', 'Decision Trees', 'Random Forests', 
    'Support Vector Machines', 'SVM', 'Convolutional Neural Networks', 'CNN', 
    'Recurrent Neural Networks', 'RNN', 'LSTM', 'Generative Adversarial Networks', 
    'GANs', 'Artificial Neural Networks', 'ANN', 'Text Classification', 
    'Recommendation Systems', 'Genomic Models', 'Clinical Decision Support Systems', 
    'Autoencoder', 'U-Net Models', 'Gradient Boosting Models', 'Information Extraction', 
    'Ensemble', 'image classification', 'sequence model', 'wasserstein gan', 
    'stochastic gradient descent', 'text classification', 'recommendation system', 
    'genomic model', 'clinical decision support system', 'variational autoencoder', 
    '3d u-net', 'gradient-boosted decision trees', 'information extraction', 
    'ensemble', 'linear regression', 'llm', 'svm', 'PathML', 'time-series analysis', 
    'multilevel-graph neural network', 'image synthesis', 'Tumor Dynamic Neural-ODE', 
    'natural language processing', 'recommender system', 'genomic prediction', 
    'cdss', 'vae', 'residual u-net', 'gbdt', 'feature extraction', 'regression model', 
    'prognostic model', 'kernel svm', 'image recognition', 'temporal data analysis', 
    'wgan', 'TDNODE', 'nlp', 'collaborative filtering', 'gene expression profiling', 
    'clinical support tool', 'denoising autoencoder', 'attention u-net', 'regularization', 
    'text analysis', 'ensemble machine learning', 'classification model', 'lasso regression', 
    'decision tree', 'svm classifier', 'medical image analysis', 'efficientnet', 
    'speech recognition', 'synthetic data', 'adam optimizer', 'sentiment analysis', 
    'content-based filtering', 'rna sequencing', 'decision support system', 'sparse autoencoder', 
    'u-net++', 'early stopping', 'entity extraction', 'ensemble method', 
    'stepwise regression', 'random forest', 'rbf kernel', 'mobilenet', 'adversarial training', 
    'drop-out layers', 'topic modeling', 'user-item interaction', 'genotype-phenotype model', 
    'computer-aided diagnosis', 'contractive autoencoder', 'u-net plus plus', 'shrinkage', 
    'information retrieval', 'bagging', 'classification tree', 'polynomial kernel', 
    'shufflenet', 'time-series prediction', 'unsupervised image generation', 
    'regularization', 'text mining', 'matrix factorization', 'genetic model', 'latent vector', 
    'skip connections', 'decision boundary', 'stacking', 'tree-based model', 'vggnet', 
    'gated recurrent unit', 'conditional gan', 'hyperparameter tuning', 'named entity recognition', 
    'reconstruction error', 'encoder-decoder architecture', 'weak learners', 'blending', 
    'out-of-bag error', 'squeeznet', 'gru', 'cgan', 'weight initialization', 
    'bottleneck layer', 'multi-scale feature extraction', 'out-of-bag evaluation', 
    'voting classifier', 'gini impurity', 'medical image segmentation', 
    'bi-directional lstm', 'progressive gan', 'activation functions', 'dimensionality reduction', 
    'region of interest', 'cross-validation', 'catboost', 'entropy', 'feature pyramid networks', 
    'attention mechanism', 'ai model', 'pgan', 'relu', 'data compression', 'feature map merging', 
    'pruning', 'fpn', 'sequence-to-sequence models', 'cyclegan', 'leaky relu', 
    'autoencoder', 'unet', 'tree depth', 'max depth', 'fully connected layers', 
    'time-series forecasting', 'stylegan', 'sigmoid', 'deepc', 'u-net', 'majority voting', 
    'min samples split', 'filter size', 'language modeling', 'latent space', 
    'batch normalization', 'transcriptomic feature vectors', 'weakly supervised unet', 
    'boosted trees', 'ensemble model', 'random state', 'pooling layers', 'vanishing gradient', 
    'discriminator loss', 'momentum', 'tfv', 'semantic segmentation', 
    'gradient boosting', 'tree depth', 'dilated convolution', 'exploding gradient', 
    'generator loss', 'early stopping', 'gradient boosting machine', 'gbm', 'boosting algorithm', 
    'random feature selection', 'wavelet transform', 'recurrent neural network', 
    'unsupervised learning', 'xavier initialization', 'boosted trees', 'gradient boosting trees', 
    'ensemble learning', 'Logic Learning Machine', 'tensorflow', 'sequential model', 
    'data augmentation', 'fused weighted deep extreme learning', 'adaboost', 'adaptive boosting', 
    'xgboost', 'extreme gradient boosting', 'categorical boosting', 'sequential model correction', 
    'dwi', 'gan', 'deep neural network', 'generator network', 'cox neural network', 
    'intelligent imaging technology', 't2-weighted imaging', 'discriminator network', 
    'gan', 'artificial neural network', 'ann', 'feedforward neural network', 
    'multilayer perceptron', 'mlp', 'cnn', 'deep learning network', 'linear regression', 'linear-regression', 'ordinary least squares', 'ols model',
    'multivariate linear model', 'multiple linear regression', 'simple linear regression',
    'gaussian linear model', 'general linear model', 'glm (linear)', 'linear lm',
    'logistic regression', 'logistic-regression', 'binomial regression',
    'binary logistic model', 'logit model', 'logit regression', 'multinomial logistic',
    'multinomial logit', 'ordinal logistic regression', 'ordinal logit',
    'probit regression', 'bayesian logistic regression', 'regularised logistic',
    'lasso logistic', 'ridge logistic', 'elastic-net logistic', 'firth logistic',
    'penalised logistic', 'sparse logistic regression', 'lasso regression',
    'ridge regression', 'elastic net regression', 'elastic-net', 'glmnet', 'glm (binomial)',
    'penalised regression', 'stepwise regression', 'backward elimination',
    'forward selection', 'poisson regression', 'quasi-poisson glm',
    'negative binomial regression', 'parametric survival regression', 'lr model', 'lr',  'support vector machine', 'support-vector machine', 'SVM', 'svm classifier',
    'svm-based classifier', 'svm model', 'svm-based model', 'svc', 'support vector classifier',
    'svr', 'support vector regressor', 'support-vector regressor',
    'kernel svm', 'linear svm', 'polynomial svm', 'poly-kernel svm',
    'rbf svm', 'gaussian svm', 'radial basis function svm', 'sigmoid svm',
    'nu-svm', 'one-class svm', 'oc-svm', 'least-squares svm', 'ls-svm',
    'probabilistic svm', 'psvm', 'structured svm', 'multiclass svm',
    'multi-class svm', 'weighted svm', 'cost-sensitive svm',
    'string-kernel svm', 'spectrum kernel svm', 'tree-kernel svm',  'decision tree', 'decision-tree', 'classification tree', 'regression tree',
    'cart', 'classification and regression tree', 'id3', 'c4.5', 'c4.5 decision tree',
    'c5.0', 'c50', 'j48', 'chaid', 'exhaustive chaid', 'oblique decision tree',
    'soft decision tree', 'conditional inference tree', 'ctree',
    'model tree', 'm5 model tree', 'binary decision tree', 'multivariate decision tree',
    'rule-based tree', 'quest tree', 'fast and frugal tree', 'rotation tree', 'DT',  'random forest', 'random-forest', 'rf classifier', 'rf model', 'rf regressor',
    'breiman forest', 'rf' , 'random decision forest', 'bagged trees', 'bagging forest',
    'extra trees', 'extremely randomised trees', 'ert', 'extratrees',
    'oblique random forest', 'rotation forest', 'quantile forest', 'qrf',
    'survival random forest', 'rsf', 'random survival forest',
    'conditional inference forest', 'cforest', 'balanced random forest',  'gradient boosting', 'gradient-boosting', 'gradient boosted trees',
    'gradient boosted decision tree', 'gbdt', 'gbrt', 'gbm', 'boosted regression tree',
    'stochastic gradient boosting', 'additive tree model', 'shrinkage tree model',
    'xgboost', 'xgb', 'extreme gradient boosting', 'xgboost classifier',
    'xgboost regressor', 'lightgbm', 'lgbm', 'light gradient boosting machine',
    'catboost', 'categorical boosting', 'histogram-based gbdt', 'dart gbdt',
    'goss gbdt', 'dart booster', 'goss booster', 'boosted survival tree',  'convolutional neural network', 'convolutional-neural-network',
    'convolutional net', 'convnet', 'cnn', 'deep cnn', 'conv neural network',
    'conv-net', '1d cnn', '1-d cnn', '2d cnn', '3d cnn', 'multi-channel cnn',
    'multiscale cnn', 'patch-based cnn', 'slice-level cnn',
    'alexnet', 'vgg', 'vgg16', 'vgg19', 'googlenet', 'inception v1', 'inception-v3',
    'inception-v4', 'inception-resnet', 'xception', 'resnet', 'resnet18', 'resnet34',
    'resnet50', 'resnet101', 'resnet152', 'resnext', 'resnext50', 'resnext101',
    'wide-resnet', 'wrn', 'seresnet', 'senet', 'squeeze and excitation network',
    'densenet', 'densenet121', 'densenet169', 'densenet201',
    'efficientnet', 'efficientnet-b0', 'efficientnet-b7', 'efficientnet-v2',
    'mobilenet', 'mobilenetv2', 'mobilenetv3', 'shufflenet', 'shufflenet-v2',
    'squeezenet', 'nasnet', 'nasnet-large', 'nasnet-mobile',
    'regnet', 'regnet-y', 'regnet-x', 'convnext', 'conv-next',
    'hrnet', 'high-resolution net', 'ghostnet', 'sknet',
    'yolo', 'yolov3', 'yolov4', 'yolov5', 'yolov6', 'yolov7', 'yolov8',
    'ssd', 'single shot multibox detector', 'retinanet', 'faster r-cnn', 'mask r-cnn',
    'cascade r-cnn', 'r-cnn', 'rcnn', 'region cnn', 'frcnn', 'mrcnn',
    'cornernet', 'centernet', 'efficientdet', 'detr', 'deformable detr',
    'hourglass net', 'deeplab', 'deep-labv3', 'deeplabv3+', 'fcn', 'fully convolutional network',
    'segnet', 'pspnet', 'gcn-cnn', 'context encoding net', 'ocrnet',
    'sigma-net', 'u-former cnn backbone (non-unet)',
    'snn', 'spiking cnn', 'temporal cnn', 'atrous cnn', 'cnns', 'u-net', 'unet', 'u_net', 'u‐net', 'unet++', 'u-net++', 'nested unet',
    'nested u-net', 'u2-net', 'u2net', 'res-unet', 'res_u-net', 'residual unet',
    'recurrent u-net', 'rcu-net', 'rcunet', 'attention u-net', 'att-unet', 'att_unet',
    'dense-unet', 'dense u-net', 'd-unet', 'multi-res unet', 'mru-net', 'mru_net',
    'v-net', 'vnet', '3d unet', '3-d unet', '3d-u-net', 'w-net', 'wnet',
    'double u-net', 'du-net', 'dual u-net', 'y-net', 'ynet', 'linknet', 'link-net',
    'ma-net', 'manet', 'inf-net', 'infnet', 'u-net-gan', 'unetgan', 'r2u-net', 'r2unet',
    'uception', 'u-ception', 'unet3+', 'unet 3+', 'coplenet', 'gated-scnn (unet)', 'vision transformer', 'vit', 'vit-base', 'vit-large', 'vit-b', 'vit-l',
    'trans-inception', 'dosvit', 'mobilevit', 't2t-vit', 'token-to-token vit',
    'deepvit', 'cct', 'compact conv-transformer', 'swin transformer', 'swin-t',
    'swin-s', 'swin-b', 'swin-l', 'swin-unet', 'swin_unet', 'swinunet',
    'pvt', 'pyramid vision transformer', 'pvtv2', 'twins-svt', 'twins-pcpvt',
    'beit', 'beitv2', 'data-efficient image transformer', 'deit', 'deit-t', 'deit-s',
    'conformer', 'conformer-vit', 'cait', 'cait-xxs24', 'consistent vit',
    'pyramidvit', 'nest-transformer', 'nesvit', 'pixt', 'pixt-small',
    'poolformer', 'hierarchical observer transformer', 'crossvit', 'cross-vit',
    'maxvit', 'spectformer', 'mamba-vit', 'mamba vision', 'segnext transformer', 'clip', 'openai clip', 'vi-clip', 'clip-med', 'medical clip', 'path-clip',
    'plip', 'plip-model', 'pulmo clip', 'radioclip', 'medclip', 'med-clip',
    'medclip-l', 'medclip-large', 'rlip (radiology clip)', 'vl-bert',
    'vilbert', 'vil-bert', 'lulaclassifier', 'kraken clip variant',
    'unified vision-language', 'unival', 'vlp unified', 'llava', 'llava-med',
    'llava-med-13b', 'chat-clip', 'otter medical', 'paella clip',
    'med-flamingo', 'flamingo-med', 'kosmos-2-med', 'mplug-owl med',
    'red-caps radiology', 'convmvlm', 'blip-2-med', 'blip-med',
    'lavis clip fork', 'uniter-med', 'ibot-vl', 's-vilt (small-vilt)',
    'pathgpt-clip', 'xo-cls vl model', 'med-palm-vl', 'gpv-2 medical', 'recurrent neural network', 'rnn', 'simple rnn', 'vanilla rnn', 'srnn',
    'long short-term memory', 'lstm', 'lstm network', 'lstm-net', 'bi-lstm',
    'bidirectional lstm', 'stacked lstm', 'deep lstm', 'conv-lstm', 'conv lstm',
    'clstm', 'spatio-temporal lstm', 'attention lstm', 'att-lstm', 'hierarchical lstm',
    'gated recurrent unit', 'gru', 'bidirectional gru', 'bi-gru', 'stacked gru',
    'indrnn', 'independent rnn', 'skip-rnn', 'phased lstm', 'clockwork rnn',
    'esn', 'echo state network', 'reservoir rnn', 'sr-lstm', 'self-regularised lstm',
    'rnng', 'recursive neural network grammar', 'tree-lstm', 'treelstm',
    'gated orthogonal recurrent unit', 'goru', 'ntm-rnn', 'neural turing lstm',
    'seq2seq rnn', 'encoder-decoder rnn', 'time-aware lstm', 't-lstm', 'graph neural network', 'gnn', 'graph convolutional network', 'gcn',
    'graph conv net', 'graph-conv', 'spectral gcn', 'chebyshev gcn', 'gcn-conv',
    'graph attention network', 'gat', 'gat-conv', 'global gat', 'gated gat',
    'graph isomorphism network', 'gin', 'graphsage', 'sage-conv', 'mean-sage',
    'pooling graph network', 'top-k pooling gnn', 'sortpool', 'dmon gnn',
    'relational graph conv net', 'rgcn', 'hetero-gnn', 'heterogeneous gnn',
    'graph transformer network', 'gtn', 'graphormer', 'glimpse gnn',
    'hypergraph neural network', 'hgnn', 'hyper-gnn', 'hgat', 'supergcn',
    'graph autoencoder', 'gae', 'variational gcn', 'vgcn', 'link-pred gnn',
    'spatial gcn', 'sgcn', 'ppi gnn', 'ppi-gcn', 'molecular gnn',
    'protein-gnn', 'mm-gnn', 'multi-modal gnn', 'graph bayesian net',
    'graph survival net', 'gcn-surv', 'gat-surv', 'generative adversarial network', 'gan', 'conditional gan', 'cgan',
    'pix2pix', 'pix2pixhd', 'dualgan', 'dual-gan', 'cycle-gan', 'cyclegan',
    'spade-gan', 'spadegan', 'stylegan', 'stylegan2', 'stylegan-v2', 'stylegan3',
    'progan', 'progressive gan', 'dcgan', 'deep convolutional gan', 'wgan',
    'wasserstein gan', 'wgan-gp', 'lsgan', 'least squares gan', 'ac-gan',
    'auxiliary classifier gan', 'srgan', 'super-resolution gan',
    'segan', 'segmentation gan', 'attention gan', 'agan', 'tgan', 'time-series gan',
    'ganomaly', 'anogan', 'big-gan', 'biggan', 'unet-gan', 'dragan', 'gan-aug', 'denoising diffusion probabilistic model', 'ddpm', 'ddpm-model',
    'ddim', 'denoising diffusion implicit model', 'latent diffusion model',
    'ldm', 'stable diffusion', 'stable-med', 'meddiffusion', 'med-ddpm',
    'score-based generative model', 'sgm', 'ncsn', 'noise-conditional score net',
    'glide diffusion', 'glide-med', 'imagen diffusion', 'palette diffusion',
    'pndm', 'pseudo numerical diffusion', 'edm diffusion', 'elucidated diffusion',
    'progressive distillation diffusion', 'sde-diffusion', 'plug-sam diffusion',
    'diffusion-seg', 'ddpm-seg', 'sr-diffusion', 'super-resolution diffusion',
    'gaussian diffusion model', 'gdm', 'classifier-free guidance diffusion',
    'ddpm-gan hybrid', 'rectified flow model', 'cold-diffusion', 'masked image modeling diffusion', 'autoencoder', 'ae', 'deep autoencoder', 'dae', 'denoising autoencoder',
    'sparse autoencoder', 'sae', 'contractive autoencoder', 'cae',
    'variational autoencoder', 'vae', 'v-autoencoder', 'β-vae', 'beta-vae',
    'cvae', 'conditional variational autoencoder', 'vector-quantised vae',
    'vq-vae', 'vq-vae-2', 'info-vae', 'ivae', 'disentangled vae',
    'factor-vae', 'vamp-prior vae', 'wae', 'wasserstein autoencoder',
    'seq-vae', 'sequence vae', 'conv autoencoder', 'convolutional ae',
    'undercomplete autoencoder', 'overcomplete autoencoder',
    'stacked autoencoder', 'sae-stack', 'deep belief autoencoder',
    'graph autoencoder', 'gae', 'variational graph autoencoder', 'vgae',
    'multimodal autoencoder', 'mm-ae', 'adversarial autoencoder', 'aae',
    'bigan encoder', 'bigan-ae', 'denoising sparse autoencoder', 'b-vae', 'large language model', 'llm', 'llm-based', 'foundation language model', 'gpt', 'gpt-2', 'gpt2', 'gpt-3', 'gpt3', 'gpt-3.5', 'gpt-4', 'gpt4', 'gpt-neo', 'gpt-j', 'gpt-neox', 'mt-nlg', 'megatron-turing', 'jurassic-2', 'palm', 'med-palm', 'medpalm', 'gemini', 'google gemini', 'gemini-pro', 'gemini-ultra', 'gemini-med', 'gatortron', 'biogpt', 'bio-gpt', 'clin-gpt', 'clinigpt', 'clinicalgpt', 'clinical-gpt', 'dxgpt', 'dx-gpt',   'medgpt', 'medi-gpt', 'med-alpaca', 'medalpaca', 'pmc-llama', 'pmc_llama', 'chatdoctor', 'doctor-glm', 'llama', 'llama-2', 'llama-med', 'alpaca', 'vicuna', 'falcon-40b', 'mpt-7b', 'bloom', 'galactica', 'mixtral', 'zephyr', 'phi-2', 'anthropic', 'claude', 'claude-2', 'claude-instant', 'deepseek', 'deepseek-llm', 'deepseek coder', 'deepseek-coder', 'chatpmd', 'meditron', 'chimera-gpt', 'samantha-med', 'bluebert', 'pubmedbert', 'medbert', 'scibert', 'biobert', 'bioredom-bert',
    'cox proportional hazards', 'cox model', 'cox regression', 'coxph',
    'cox-ph', 'coxphfit', 'proportional hazards model', 'ph model',
    'proportional hazards regression', 'kaplan-meier', 'kaplan-meier',
    'weibull survival model', 'exponential survival model',
    'log-logistic survival', 'parametric survival model',
    'piecewise exponential model', 'flexible parametric survival',
    'fpsm', 'aft survival model', 'accelerated failure time model',
    'random survival forest', 'rsf', 'survival random forest',
    'conditional inference survival tree', 'fine-gray regression',
    'fg model', 'subdistribution hazards model', 'deepsurv', 'deep-surv', 'deepsurv-net', 'deep cox network',
    'deep-cox', 'deepcox', 'cox-nnet', 'coxnnet', 'cox-nnet v2',
    'nnet-survival', 'nnsurv', 'deepph', 'deep-ph', 'deepphnet',
    'scnn-cox', 'survnet-cox', 'deepcoxmixture', 'neural cox model', 'deephit', 'deep-hit', 'deep-hit network', 'dynamic deephit',
    'deephit+', 'deephit-plus', 'deep cif', 'cif-net',
    'competing risk deep net', 'crnnet', 'compnet',
    'cause-specific dlnn', 'dni-net', 'crmnet', 'trans-surv', 'transsurv', 'survformer', 'surv-former',
    'bert-survival', 'survbert', 'swin-survival', 'vit-survival',
    'informersurv', 'sparse transformer survival', 'surv-transformer',
    'longformer-surv', 'transformer survival model', 'surv-attention net', 'deepvariant', 'deep-variant', 'deeptrio', 'deep-trio',
    'deepsomatic', 'deep-somatic', 'clair', 'clairvoyante',
    'clair3', 'pepper-margin-dv', 'pepper-dv', 'octopus variant caller',
    'longshot', 'sniffles2', 'banquo', 'vartox', 'peppy',
    'sherloc', 'hend', 'elongate', 'deepaligner', 'nanovar',  'arriba', 'arriba-dl', 'jaffa', 'jaffa-clin',
    'star-fusion', 'fusioncatcher', 'pizzly', 'defuse',
    'fusionmap', 'chimera-scan', 'fusioninspector', 'manta-fusion',
    'soccer-fusion', 'gcook-fusion', 'ericscript', 'fuseq', 'hig2vec', 'prottrans', 'prottrans-t5', 'esm-1b', 'esm-2',
    'protbert', 'prot-bert', 'dnabert', 'dna-bert', 'genformer',
    'dnaformer', 'allele transformer', 'pangenome transformer',
    'splicetransformer', 'nnformer-gene', 'graphprot', 'graph-prot',
    'gloe2vec', 'graph genome network', 'graphgnn-omics',
    'graphsage-omics', 'protein clip', 'rtransformer', 'seqformer', 'k-nearest neighbours', 'k-nearest neighbors', 'k nearest neighbour',
    'k nearest neighbor', 'knn', 'k-nn', 'kNN classifier', 'kNN regressor',
    'distance-weighted kNN', 'radius neighbors classifier',
    'kd-tree kNN', 'ball-tree kNN', 'local weighted kNN',
    'fuzzy kNN', 'typicality-based kNN', 'ranked kNN',
    'adaptive kNN', 'improved kNN', 'sknn', 'naive bayes', 'naïve bayes', 'bayesian classifier',
    'gaussian naive bayes', 'multinomial naive bayes',
    'bernoulli naive bayes', 'complement naive bayes',
    'categorical naive bayes', 'semi-naive bayes',
    'tree-augmented naive bayes', 'weighted naive bayes',
    'kernel naive bayes', 'locally weighted naive bayes',
    'flexible bayes', 'continuous naive bayes',
    'naive bayes regressor', 'multimodal transformer', 'multi-modal transformer', 'mm-transformer',
    'mmt', 'cross-modal transformer', 'fusion transformer',
    'perceiver io', 'perceiver-ar', 'medical perceiver',
    'unified transformer', 'uni-transformer', 'bi-modal transformer',
    'vl-transformer', 'vil transformer', 'radgpt', 'radimagegpt',
    'med-gpt-v', 'mmgpt', 'fusionformer', 'mmt-bert',
    'video-image-text transformer', 'graph-text-image transformer', 'graph integrator', 'graph integration network',
    'graph fusion network', 'multiomic gnn', 'multi-omics gnn',
    'omics graphsage', 'heterograph fusion', 'graph hetero fusion',
    'graph multimodal aggregator', 'graph attention fusion',
    'graph feature fusion', 'graph neural integrator',
    'gnn-fuser', 'graph registry network', 'non-euclidean graph integrator', 'artificial neural network', 'ann', 'multilayer perceptron', 'mlp',
    'feed-forward neural network', 'ffnn', 'fully connected net',
    'deep feed-forward net', 'dense neural network', 'dnn',
    'stacked perceptron', 'bp-network', 'back-propagation network',
    'radial basis function network', 'rbf-net', 'probabilistic neural net',
    'pnn', 'generalised regression neural net', 'grnn',
    'cascade correlation net', 'cc-network', 'extreme learning machine',
    'elm', 'deep elm', 'functional link neural net', 'flnn',
    'adaptive resonance theory net', 'art-2 network', 'counterpropagation net',
    'cpn', 'gmdh neural net', 'group method data handling net',
    'bipolar sigmoid net', 'threshold logic unit', 'clinical decision support system', 'cdss', 'computerised decision support',
    'clinical decision aid', 'decision support engine', 'intelligent cpoe',
    'computer-aided diagnosis', 'cadx engine', 'computer-aided detection tool',
    'cade module', 'virtual nodule clinic', 'optellum system',
    'paige detect suite', 'paige prostate ai', 'watson for oncology',
    'path_ai dx assistant', 'guardant inform', 'imagenome cdss',
    'radgpt-assistant', 'echonous guidance ai', 'viz-ai stroke',
    'derm-engine assist', 'lung-rnd assist', 'skinvision pro',
    'qure.ai chestx', 'gleamer boneview', 'veritone contact ai', 'recommendation system', 'recommender engine', 'rec-sys',
    'therapy recommender', 'treatment recommender', 'drug-combo recommender',
    'personalised regimen suggestor', 'neural collaborative filtering',
    'ncf model', 'matrix factorisation recommender', 'mf recommender',
    'deep factorisation machine', 'deepfm', 'wide-and-deep network',
    'context aware recommender', 'caware recommender', 'knowledge graph recommender',
    'kg-rec', 'hybrid recommender', 'content-based recommender',
    'session-based recommender', 'seq-recommendation net',
    'co-clinical recommender', 'genomic-drug matcher', 'oncoassist recommender',
    'dose-optimizer rec', 'radiation plan recommender', 'ensemble learning', 'ensemble classifier', 'ensemble regressor',
    'model stacking', 'stacked ensemble', 'stacking learner',
    'blended ensemble', 'blend model', 'soft voting committee',
    'hard voting committee', 'majority voting ensemble', 'weighted voting ensemble',
    'bagging ensemble', 'bootstrap aggregating', 'pasting ensemble',
    'random subspace ensemble', 'heterogeneous ensemble', 'homogeneous ensemble',
    'deep ensemble', 'snapshot ensemble', 'super learner', 'meta-learner',
    'mixture of experts', 'moe ensemble', 'boosted ensemble',
    'gradient ensemble', 'population based ensemble', 'committee machine',
    'bayesian model averaging', 'text-cnn', 'kim-cnn', 'char-cnn', 'charcnn', 'fasttext-classifier',
    'hierarchical attention network', 'han-classifier', 'han-att',
    'bi-lstm-attention', 'bilstm-att', 'text-slimlstm', 'rcnn-text',
    'text-gcn-classifier', 'tgcn', 'bayesian text classifier',
    'tfidf-svm-text', 'linear text classifier', 'transformer text classifier',
    'tinybert-classifier', 'distilbert-classifier', 'electra-text model',
    'albert-text classifier', 'roberta-text cls', 'longformer-classifier',
    'spanbert-classifier', 'xlnet-text classifier', 'hyperbolic text embedder',
    'lightweight text net', 'clinical-note classifier', 'abstract-topic net',
    'pubmed-bert classifier', 'med7-ner', 'med7 extractor', 'medspacy-ner', 'biobert-ner',
    'biobert-crf', 'clinicalbert-ner', 'bluebert-ner',
    'spanbert-ner', 'scispacy-ner', 'en_ner_bc5cdr_md',
    'dysner', 'disease-ner', 'chemprot-ner', 'gatortronnlp-ner',
    'bertje-ner-med', 'roberta-biomed-ner', 'bilstm-crf ner',
    'charlstm-crf ner', 'gazetteer-enhanced ner', 'rule-based ner (med)',
    'ontology-driven ner', 'contextual span extractor',
    'symptom extractor net', 'tnm-extraction model', 'medexa ie model',
    'uima cTakes ner', 'deepmedic ner', 'pharmaconer extractor',
    'ehr entity linker', 'relationship extractor cnn', 'graphsurvnet', 'graph-survival network', 'gnn-survival model',
    'graph survival transformer', 'gst-net', 'hetero-surv gnn',
    'sage-survival net', 'graphsage-survival', 'gin-survival',
    'gat-survival++', 'graph-cox surv', 'geo-survnet',
    'deep graph hazard model', 'dg-hazard', 'adaptive graph survival',
    'ppi-surv gnn', 'multiomic-surv gnn', 'spatial graph surv',
    'attention graph survival', 'temporal graph survival',
    'integrated graph survival network', 'gbm-survival', 'gradient boosted survival analysis', 'weighted random forest', 'neural network classifier', 'whole slide images', 'WSI', 'MALDI', 'densenet', 
    'resnet', 'inception', 'alexnet', 'multi-layered cnn', 'convnet', 'transformers', 'Bidirectional Encoder Representations from Transformers', 'BERT', 'ViT', 'Vision transformer'
    ]

def uniq_lower(lst):
    return list(OrderedDict.fromkeys(w.lower() for w in lst))

onco = uniq_lower(raw_onco)
ai   = uniq_lower(raw_ai)

def compile_pattern(keywords):
    esc = sorted((re.escape(w) for w in keywords), key=len, reverse=True)
    return re.compile(r'\b(?:' + '|'.join(esc) + r')\b', re.IGNORECASE)

onc_pat = compile_pattern(onco)
ai_pat  = compile_pattern(ai)

cols = ['Authors', 'Article Title', 'Source Title', 'Author Keywords', 'Abstract']
df['combined'] = df[cols].agg(' '.join, axis=1).str.lower()

mask = df['combined'].str.contains(onc_pat) & df['combined'].str.contains(ai_pat)
result = df[mask].drop(columns='combined')

result.to_excel(r"D:\results\filtered_dataset.xlsx", index=False)
print(f"Відфільтровано {len(result)} статей")